export const SEARCH_MOVIES_START = 'SEARCH_MOVIES_START';
export const SEARCH_MOVIES_ERROR = 'SEARCH_MOVIES_ERROR';
export const SEARCH_MOVIES_COMPLETE = 'SEARCH_MOVIES_COMPLETE';

export const SEARCH_MOVIE_BY_ID_START = 'SEARCH_MOVIE_BY_ID_START';
export const SEARCH_MOVIE_BY_ID_ERROR = 'SEARCH_MOVIE_BY_ID_ERROR';
export const SEARCH_MOVIE_BY_ID_COMPLETE = 'SEARCH_MOVIE_BY_ID_COMPLETE';
